version: '3.4'

services:
    parse:
        build: .
        environment:
            PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
            PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
            MONGODB_URI: mongodb://${MONGO_PARSE_USER}:${MONGO_PARSE_PASSWORD}@db:27017/${MONGO_PARSE_DB}
            PORT: ${PORT}
            PARSE_SERVER_URL: http://parse:${PORT}/parse
            PARSE_PUBLIC_SERVER_URL: http://localhost:${PORT}/parse
            PARSE_SERVER_CLOUD: /parse/cloud/main.js
            PARSE_SERVER_MOUNT_GRAPHQL: 1
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${PORT}:${PORT}
        #volumes:
        #    - ./index.js:/parse/index.js #Uncomment this to customize your parse server
        #    - ./cloud:/parse/cloud #Uncomment this to provide your own cloud code
        restart: always
        depends_on:
            - db
        command: ["npm", "start"]
    dashboard:
        image: parseplatform/parse-dashboard:latest
        command: parse-dashboard --dev
        volumes:
            - ./parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        ports:
            - 127.0.0.1:4040:4040
        depends_on:
            - parse
    db:
        build:
            context: .
            dockerfile: ./Dockerfile_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_PARSE_DB}
        ports:
            - 27017:27017
    #Uncomment volumes below to persist mongo data. Make sure to change directory to store data locally
   #     volumes:
   #         - /My/Encrypted/Drive/db:/data/db #Mount your own drive
   #         - /My/Encrypted/Drive/logs:/mongologs #Mount your own drive
