version: '3.4'

services:
    parse:
        build: .
        environment:
            PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
            PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
            PARSE_SERVER_DATABASE_URI: postgres://${PG_PARSE_USER}:${PG_PARSE_PASSWORD}@db:5432/${PG_PARSE_DB}
            PORT: ${PORT}
            PARSE_SERVER_URL: http://parse:${PORT}/parse
            PARSE_PUBLIC_SERVER_URL: http://localhost:${PORT}/parse
            PARSE_SERVER_CLOUD: /parse/cloud/main.js
            PARSE_SERVER_MOUNT_GRAPHQL: 1
        ports:
            - ${PORT}:${PORT}
        restart: always
        volumes:
            - ./index.js:/parse/index.js
            - ./cloud:/parse/cloud
        depends_on:
            - db
    parse-test:
        image : parseplatform/parse-server:latest
        environment:
            PARSE_SERVER_TEST_DB: postgres
            PARSE_SERVER_TEST_DATABASE_URI: postgres://db:5432/parse_server_postgres_adapter_test_database
            #PARSE_SERVER_LOG_LEVEL: debug
        ports:
            - 127.0.0.1:1400:${PORT}
        restart: always
        depends_on:
            - db
        command: npm run test
    dashboard:
        image: parseplatform/parse-dashboard:2.0.5
        command: parse-dashboard --dev
        volumes:
            - ./parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        ports:
            - 127.0.0.1:4040:4040
        depends_on:
            - parse
    db:
        build:
            context: .
            dockerfile: ./Dockerfile_postgis
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PG_PARSE_USER: ${PG_PARSE_USER}
            PG_PARSE_PASSWORD: ${PG_PARSE_PASSWORD}
            PG_PARSE_DB: ${PG_PARSE_DB}
    #Uncomment volumes below to persist postgres data. Make sure to change directory to store data locally
    #volumes:
    #    - ./data:/var/lib/postgresql/data
