version: '3.4'

services:
    postgis:
        build: .
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PG_PARSE_USER: ${PG_PARSE_USER}
            PG_PARSE_PASSWORD: ${PG_PARSE_PASSWORD}
            PG_PARSE_DB: ${PG_PARSE_DB}
    parse:
        image: parseplatform/parse-server:latest
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
            PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
            PARSE_SERVER_DATABASE_URI: postgres://${PG_PARSE_USER}:${PG_PARSE_PASSWORD}@postgis:5432/${PG_PARSE_DB}
            PARSE_SERVER_TEST_DB: postgres
            PARSE_SERVER_LOG_LEVEL: debug
        ports:
            - 1337:1337
        restart: always
        depends_on:
            - postgis
