version: '3.4'

services:
    parse:
        image: parseplatform/parse-server:latest
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
            PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
            PARSE_SERVER_DATABASE_URI: postgres://${PG_PARSE_USER}:${PG_PARSE_PASSWORD}@db:5432/${PG_PARSE_DB}
            PARSE_SERVER_MOUNT_GRAPHQL: 1
        ports:
            - 1337:1337
        restart: always
        depends_on:
            - db
    dashboard:
        image: parseplatform/parse-dashboard:latest
        command: parse-dashboard --dev
        volumes:
            - ./parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
        ports:
            - 127.0.0.1:4040:4040
        depends_on:
            - parse
    db:
        build: .
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PG_PARSE_USER: ${PG_PARSE_USER}
            PG_PARSE_PASSWORD: ${PG_PARSE_PASSWORD}
            PG_PARSE_DB: ${PG_PARSE_DB}
