version: '3.4'

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile_test
    links:
        - parse
        - parse-test
        - dashboard
        - dashboard-test
    volumes:
        - ./scripts/wait-for-parse.sh:/app/wait-for-parse.sh
        - ./scripts/test.sh:/app/test.sh
    depends_on:
      - parse
      - parse-test
#      - db
      - dashboard
      - dashboard-test
    command: ["/app/wait-for-parse.sh", "db", "bash", "/app/test.sh"]
  parse:
    build: .
    environment:
        PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
        PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
        PARSE_SERVER_DATABASE_URI: postgres://${PG_PARSE_USER}:${PG_PARSE_PASSWORD}@db:5432/${PG_PARSE_DB}
        PORT: ${PORT}
        PARSE_SERVER_URL: http://parse:${PORT}/parse
        PARSE_PUBLIC_SERVER_URL: http://localhost:${PORT}/parse
        PARSE_SERVER_CLOUD: /parse/cloud/main.js
        PARSE_SERVER_MOUNT_GRAPHQL: 1
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
        - ${PORT}:${PORT}
    volumes:
        - ./scripts/wait-for-postgres.sh:/parse/wait-for-postgres.sh
    #    - ./index.js:/parse/index.js
    #    - ./cloud:/parse/cloud
    command: ["./wait-for-postgres.sh", "db", "npm", "start"]
    links:
        - db
    depends_on:
        - db
  parse-test:
    image: parseplatform/parse-server:latest
    environment:
      PARSE_SERVER_TEST_DB: postgres
      PARSE_SERVER_TEST_DATABASE_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/parse_server_postgres_adapter_test_database
      #PARSE_SERVER_LOG_LEVEL: debug
      PARSE_SERVER_APPLICATION_ID: E036A0C5-6829-4B40-9B3B-3E05F6DF32B2
      PARSE_SERVER_MASTER_KEY: E2466756-93CF-4C05-BA44-FF5D9C34E99F
      PARSE_SERVER_DATABASE_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/parse_server_postgres_adapter_test_database
    ports:
      - 1400:1337
    links:
        - db
    #volumes:
    #    - ./scripts/wait-for-postgres.sh:/parse-server/wait-for-postgres.sh
    restart: always
    depends_on:
        - db
    #command: ["/parse-server/wait-for-postgres.sh", "db", "npm", "run", "test"]
  dashboard:
    image: parseplatform/parse-dashboard:2.0.5
    command: parse-dashboard --dev
    volumes:
        - ./parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json
    ports:
        - 4040:4040
    links:
        - parse
    depends_on:
        - parse
  dashboard-test:
    image: parseplatform/parse-dashboard:2.0.5
    command: parse-dashboard --dev
    volumes:
        - ./parse-dashboard-config-test.json:/src/Parse-Dashboard/parse-dashboard-config.json
    ports:
        - 8040:4040
    links:
        - parse-test
    depends_on:
        - parse-test
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_PARSE_USER: ${PG_PARSE_USER}
      PG_PARSE_PASSWORD: ${PG_PARSE_PASSWORD}
      PG_PARSE_DB: ${PG_PARSE_DB}
      PARSE_TEST: 1
